#!/bin/sh

set -e

pkgos_adduser () {
        local VAR_UG_PKG_NAME
        VAR_UG_PKG_NAME=${1}

        # Create user and groups if they don't exist
        if ! getent group ${VAR_UG_PKG_NAME} > /dev/null 2>&1 ; then
                addgroup --quiet --system ${VAR_UG_PKG_NAME}
        fi
        if ! getent passwd ${VAR_UG_PKG_NAME} > /dev/null 2>&1 ; then
                adduser --system \
                        --home /var/lib/${VAR_UG_PKG_NAME} \
                        --no-create-home \
                        --quiet \
                        --disabled-password \
                        --shell /bin/bash \
                        --group ${VAR_UG_PKG_NAME}
        fi
}

pkgos_var_user_group () {
        local VAR_UG_PKG_NAME
        VAR_UG_PKG_NAME=${1}

        pkgos_adduser ${VAR_UG_PKG_NAME}

        # Create /var/{lib,log}/<package> with that user/group if it doesn't exist
        if [ ! -d /var/lib/${VAR_UG_PKG_NAME} ] ; then
                mkdir -p /var/lib/${VAR_UG_PKG_NAME}/cache
        fi
        chown ${VAR_UG_PKG_NAME}:${VAR_UG_PKG_NAME} /var/lib/${VAR_UG_PKG_NAME}
        if [ "${VAR_UG_PKG_NAME}" = "nova" ] ; then
                chmod 755 /var/lib/nova
        else
                chmod 0750 /var/lib/${VAR_UG_PKG_NAME}
        fi
        if [ ! -d /var/log/${VAR_UG_PKG_NAME} ] ; then
                mkdir -p /var/log/${VAR_UG_PKG_NAME}
        fi
        chown ${VAR_UG_PKG_NAME}:${VAR_UG_PKG_NAME} /var/log/${VAR_UG_PKG_NAME}
        chmod 0750 /var/log/${VAR_UG_PKG_NAME}
}

pkgos_write_new_conf () {
        local WRITE_N_CONF_PKG_NAME CONF_FNAME
        WRITE_N_CONF_PKG_NAME=${1}
        CONF_FNAME=${2}

        SRC_PATH=/usr/share/${DPKG_MAINTSCRIPT_PACKAGE}/${CONF_FNAME}
        DST_DIR=/etc/${WRITE_N_CONF_PKG_NAME}
        DST_PATH=${DST_DIR}/${CONF_FNAME}
        if [ ! -d ${DST_DIR} ] ; then
                mkdir -p ${DST_DIR}
        fi
        chmod 0750 ${DST_DIR}
        chown ${WRITE_N_CONF_PKG_NAME}:${WRITE_N_CONF_PKG_NAME} ${DST_DIR}
        if [ ! -e ${DST_PATH} ] ; then
                install -D -m 640 -o ${WRITE_N_CONF_PKG_NAME} -g ${WRITE_N_CONF_PKG_NAME} ${SRC_PATH} ${DST_PATH}
        fi
}

if [ "$1" = "configure" ] ; then
	pkgos_var_user_group murano-agent
	pkgos_write_new_conf murano-agent muranoagent.conf
fi

#DEBHELPER#

exit 0
